formatter: markdown

content: |-
  # terraform-aws-cloudtrail
  
  This module creates a CloudTrail trail, a CloudWatch log group, and an S3 bucket for storing CloudTrail logs.

  ## Usage

  ### Basic

  ```hcl
  {{ include "examples/complete/cloudtrail/terragrunt.hcl" }}
  ```

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true